name: CI - Testes Automáticos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # ou a versão que você usa localmente

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com Pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Gerar relatório de cobertura
        run: |
          pytest --cov=src --cov-report=term-missing

      - name: Verificar qualidade do código (Flake8)
        run: |
          flake8 src tests --max-line-length=100 --ignore=E203,W503
